### ISSUE TITLE
Ruined my install, any way to fix?

### ISSUE THREAD

**Issue by StarrKiss** [paju1986/PlasmaConfSaver#4] opened 2019-06-04 21:30 UTC
Saved my layout, created  a new one, tried to switch to it, background wen black, latte dock dissapeared, and in settings, all addons are GONE. Cannot switch back without the SAME THING happening again. I try to import my exported package, and it doesnt work either. Please help me get my config files back! I cant even extract my package using Ark!

**Comment by StarrKiss** [comment] 2019-06-04 22:26
Hello, I need this fixed ASAP. Can I please have some help?

**Comment by bvbfan** [comment] 2019-06-05 05:31
Consider not using `$(pwd)/.config` instead use `StandardPaths.standardLocations(StandardPaths.GenericConfigLocation)` and `StandardPaths.standardLocations(StandardPaths.GenericDataLocation)` 
also never delete user configuration (rm -Rf $(pwd)/.local/share/plasma), it cannot be reverted, instead backup them by rename. After that user can revert or you can offer that as button revert old configuration. After all plasma package can do all that for you, now your code looks like malware.

**Comment by StarrKiss** [comment] 2019-06-05 05:57
I was able to revert it by using certain flags on the exported package and reimporting the configs. in the future, would it be possible to make it so this issue doesnt come up again? This was a rice I spent months on, (including editing theme svgs) so I am hesitant to use this again (despite its useful features) until I can be assured that it works. Sorry for overreacting earlier, I was just very worried that my rice had dissapeared. This is, like, version 1.0 so its bound to have bugs and issues. This is something that should be stock in plasma and will be very useful and cool once it is polished up.  Thank you very much for responding. Additional details for how this bug are triggered: Kubuntu 18;10, latte dock (which I think may have caused the issue) and custom theme svgs. 32 gigs of ram, Ryzen Threadripper 2950x, GTX 1070ti. /home/ is on an ssd.

**Comment by paju1986** [comment] 2019-06-05 06:15
Hello.

Sorry for the problem your commented, Im glad your were able to get your configs back.  I will try the suggestions bvgfan commented earlier as soon as i can to see if we can solve this problem once and for all.  Your are not the fisrt that commented me a problem like that, despite on my test never had those problems. 

I deleted all releases on kde store untill i can figure this out, this is a serius issue.

Regards.

**Comment by paju1986** [comment] 2019-06-05 06:26
One question. Are you using x11 or wayland on your session? I know a issue like that happen when using wayland...

**Comment by StarrKiss** [comment] 2019-06-05 12:42
X11

**Comment by paju1986** [comment] 2019-06-05 20:16
It appears that the problem is that the shell scripts commands used to reload the configuration are executed on a asynchronous way so sometimes depending on the machine it tries to reload plasmashell before the files were actually restored messing up the process. I have moved the commands to a external shell script in the hope that would fix the problem, i did a few test on my pc and it worked fine but more testing is needed, also it brokes lattle-dock support for now but should be easy to fix.

**Comment by StarrKiss** [comment] 2019-06-05 20:18
Sounds good, it's a great idea

**Comment by VladimirMikulic** [comment] 2019-06-06 08:32
@paju1986 is there a way to prevent asynchronous behaviour and delay the script execution somehow without moving the commands to the external script? Moving commands is just a "hack" or workaround, in my opinion, it may not work always. Can you manually set a delay? Since I am not an experienced with Plasma scripting, I'll try to help you by testing this in a few VMs.

**Comment by paju1986** [comment] 2019-06-06 08:49
I think moving the shell commands to a script is the correct way anyways, it makes the code cleaner and easier to understand not mixing bash with the qml. With the commands executed secuencially on a shell script should no longer be a problem of files not being fully restored before plasmashell is restarted. I applied the @bvbfan suggestions too and I no loger use rm to delete the configs before restoring the saved ones but mv instead to make  .bak files, so just in case something fails those can be later restored manually. I still have to fix the latte-dock support, i expect i could make a testing realease soon. Thanks @VladimirMikulic for the help in testing.

**Comment by paju1986** [comment] 2019-06-06 17:43
I have published a experimental release with all the changes. Please test. PLEASE BACKUP YOUR DATA BEFORE TRYING or EXPERMIENT ON A VM Thanks you!

**Comment by VladimirMikulic** [comment] 2019-06-06 21:56
@paju1986 I have some good news and bad news.
The good news is that extension works properly, there is no black screen and disappearing desktop.

![Screenshot 2019-06-06 23:44:34](https://user-images.githubusercontent.com/35997844/59069112-86e39d00-88b6-11e9-93a8-375ba21af1a8.png)

The bad news is that after saving my desktop, I can't launch apps from the KDE launcher. 
This is not a problem for me since I use keyboard shortcuts to start apps, but for other users, this will be a problem that you'll have to fix somehow. I assume that this happens because the extension reloads desktop, so it may crash/disable the launcher.

**Comment by paju1986** [comment] 2019-06-07 06:17
That's weird, I will have to investigate it. It uses kquitapp5 plasmashell && kstart5 plasmashell after restoring all the saved config files for restarting plasmashell, those commands are supossed to restart plasmashell gracefully without crashes.

Maybe i should stop plasmashell before trying to restore the config files, and starting it after.

**Comment by paju1986** [comment] 2019-06-07 16:40
OK, It seems that when doing kquitapp5 plasmashell, becase it was stoping plasmashell and the script was attached to it, it stoped the script too. so what i have done is to use nohup for calling the script detached from plasmashell. 
I have published the new experimental version, so please test. Thanks you!

please, make sure you start fresh with no old configs saved.

**Comment by VladimirMikulic** [comment] 2019-06-07 17:12
@paju1986 Unfortunately this doesn't fix the issue.

**Comment by VladimirMikulic** [comment] 2019-06-07 17:19
@paju1986 Now it is even worse. Black/disappearing screen is back.
You should revert the changes.

**Comment by paju1986** [comment] 2019-06-07 17:29
It works perfectly fine on my rig, so i dont understand what is happening, im going to setup a vm with kubuntu 18.04 so i cant test there if that makes any difference

**Comment by paju1986** [comment] 2019-06-07 17:38
can you try in your shell if you have the command nohup available? maybe is that...

**Comment by VladimirMikulic** [comment] 2019-06-07 17:41
@paju1986 nope it is not. I have nohup installed and I know what it does.

**Comment by paju1986** [comment] 2019-06-08 08:00
OK, i tested it on a kubuntu 18.04 vm and I was able to reproduce the issue, turn out that on kubuntu for some reason you have to pass --windowclass plasmashell and --window Desktop to kstart5 for it to work..., now seems to work fine on kubuntu, could you give it a try? thanks you!!

**Comment by VladimirMikulic** [comment] 2019-06-08 08:24
Now everything works fine, good job, but you still might encounter an issue with this "hack". For example, I don't use Konsole as my terminal emulator, I use Tilix. I didn't have Konsole installed on my system and I had to install it. It is not a problem for me, but other users won't look at your script to see why it is not working. You should somehow get the terminal emulator of the system or at least setup switch / if statements and test for popular terminals and execute a command with one that is installed on the user's system. This is not a high severity issue, just something to keep in mind for the future.

**Comment by paju1986** [comment] 2019-06-08 09:19
That is a hack to fix the problem with the kickoff menu stoping working after reloading plasma. I dont know why that happens but on my archlinux machine that is not necessary and everything works fine without it. I dont quite understand yet what is the difference there from arch to kubuntu but you are right, the problem is that there are many terminal emulators out there to support them all and i dont even know if others work, so problably by now i just make konsole as a requieriment for the widget as it is the standard kde terminal emulator.

**Comment by VladimirMikulic** [comment] 2019-06-08 10:51
Yeah, just specify Konsole as a dependency.

**Comment by paju1986** [comment] 2019-06-08 11:36
Since has been reported to being correctly working now i close the issue.

**Closed as completed by paju1986** 2019-06-08 11:36 UTC
